
export default [
  { name: "Red"},
  { name: "Pink"},
  { name: "Purple"},
  { name: "Deep Purple"},
  { name: "Indigo"},
  { name: "Blue"},
  { name: "Light Blue"},
  { name: "Cyan"},
  { name: "Teal"},
  { name: "Green"},
  { name: "Light Green"},
  { name: "Lime"},
  { name: "Yellow"},
  { name: "Amber"},
  { name: "Orange"},
  { name: "Deep Orange"},
  { name: "Brown"},
  { name: "Grey"},
  { name: "Blue Grey"},
  { name: "Black"},
]
